travis:
  secure:
    BINSTAR_TOKEN: q4QbA3bJskrLAdgfRpTvIDSq/7ezn6DttgTU63PvT1W4dOGM3dMgRqKvElMH6ah5VK7sCspQvwXU4AQnHR6rshunQWpV9iPOv9HTq6ZL2tCPAr8qC0CeipJa4QKVWfwLwoECYkXdF/ChTr/OjHFqUAFR8O4RY3Lgsfrl//HMua3k5zYJmxrlDgJgQ/zDPZQe4Mp7neopsLeg0cdf22hTwardvOMw3ANyGX06tx3wtQpxfGlxEptyf2xZM2Tio4cAJ4fioBaFuV7w5hyRRRFMO3Q+SBX64ohCLioM9wCGycTqdKmzFXJDM9OmSziFB79dXuuG8Xpczij2c9hFxr6g/k3w2YlDZL/be8yWlAveCIdzT5ScRg9YP2iKo7e7qTUnxDDfZV/7vcjLtQ2j6EdUM/8IKLrYk5ws+TpRcR34lceULHoL42TOXhOJTIHPgeKGS7ACXY0qxs3RMQCY+8ReLqVwuUj1Ic9q4ckpb7aoHHXlSsDn0DzJeXmYmPAz7q2741TZuSjBeXnBSwZKRImZLqaDbVELNzGg0XCFWeisMSHEpIMx5elpGrva1izQEmukR99EBsDmOIybSmgJbp5HGxSey15/vzjc2m5rjhpqrkridy3nsNMSrzSm1WPL3sIiQ04XKiGMrTVsErvTuAH3u6JPs1EzJFHAbPtrafO5mbI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
