travis:
  secure:
    BINSTAR_TOKEN: oHL2SajWjgh/7RMH+CY9qp2Gjt1Vgl5DtvLdbFK821UIrNz80ybshdAbeMkfabQv0OiARO3jEUTxfqo/YdQ4Hnpt8FH3bHEM6/Vl5o6HjoazZP88JyJiV7Dac96YH4rMfyij7oKVuUNXMmfGgplNzHnnSDpHHcLm+kvbX/tdlH5/Bdo1O6va1Cwh2bklROeqpfo9MJ1Zu7bf3ggrErPj87uFkqKCUhjEcw/gZRZo40Escx8GF1hxE+PrSNA0dRV1fvWoju1yIA5kBiASUPHS3QD1UV73NMgaVrQEKDsMzdcctdU/HqaMBHwQy5hQLq25hbONAvV5qSTLG3YC8UWwy/hyPAVmp+t6ZRi4t9OIRfKbZT0i5Ler8fTmTRlSD2SMQ58dgFoFaQq8NumWNweILrjdTk93+rWOVW+h6pDmh8nesYbx26DumBJ+PtH8KZWgr4IhLXbl6QOO3MdGfoooC/XT3wQmglIAt16L3a0j6iELa3nvWwVNpDj33O+BHbCgKsMm4a2Cv8T3wQ9zHwMi36/vD8R1XqanMpcZeExArJoSE47bwE64KPNzvZ8CRmu1XFOjkmO7GK/Z97Sf8tZWaJFRbC+NyBsdZx0wKxOkWkbTPaKF+y0F03AM5tAyPMGtZEEUpuVuVX8fCw5NVmTLBg+TH0VzwxAla7XGzO/JHBs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
